### PR TITLE
Path.mergepath

### PR DESCRIPTION
**Pull request by funkyfuture**
so here it is.

the first commit doesn't relate to the functionality, but i needed it when i worked on it.
i can purge it, if you want to.

### CODE REVIEW

**Comment by funkyfuture** [comment]
okay, i threw that out as it would break travis. however, i added unittest2 for Python 2.6 to make use of `unittest.TestCase.assertSetEqual`.

**Comment by jaraco** [comment]
Including unittest2 as an extra will cause it to be installed for all users on Python 2.6 (not just when running tests). I'd like to drop use of unittest anyhow as I prefer py.test for simple asserts. So I'm going to omit that commit, but instead rewrite it not to rely on unittest.

I'll also rename `mergetree` to `merge_tree` for preferred naming convention.

Thanks for the contrib.

**Comment by jaraco** [comment]
@funkyfuture I'm having [some trouble with my git client](https://bitbucket.org/durin42/hg-git/issues/123). Could you revise this PR to include only the mergetree commit?

**Comment by funkyfuture** [comment]
yup, done.

**Pull request merged**
