### PR TITLE
Adds note to api.rst

### PR DESCRIPTION
**Pull request by funkyfuture**
i did this with github's web-editor. i haven't checked what's rendered.

### CODE REVIEW

**Comment by jaraco** [comment]
Thanks for this. I had already put the documentation in the Path class as 6c08c008762ff. I've pushed that change to the [published documentation](http://pythonhosted.org/path.py/api.html) for your review. I prefer this location, as it will show it command-line help and the source, as well as the documentation. Will that suffice, or do you think there should be a separate note in the API docs?

**Comment by funkyfuture** [comment]
yes, i saw this. but i think it deserves a prominent note. meanwhile i noticed that this not only true for functions from `shutil`, so that part can be removed.

what about this:

```
.. important::
    The documented methods' signatures signatures are not always correct.
    See :class:`Path`.
```

**Comment by jaraco** [comment]
> i haven't checked what's rendered.

By the way, did you know you can easily check what's rendered by running `setup.py build_sphinx` and then opening the docs in build/sphinx/html/index.html?

**Comment by jaraco** [comment]
> what about this:

I do see the value in calling out the warning with some different formatting (like `..important`). The warning is a little vague, but it does draw the appropriate attention. It does seem a little weird that it will link to class that is the next thing in the document, but I guess that's fine.

**Comment by funkyfuture** [comment]
> did you know you can easily check what's rendered..

yeah, but i hadn't used a local fork, but the github-web-editor.

shall i fix this pr? or you make your own change. i don't care who's doin' it.

one thing came through my mind: if Sphinx inspected parsed python-objects after importing the source code, it may be possible to substitute `src` to `self` in their `__docstring__` to achieve a proper documentation. do you know whether Sphinx works this way?

**Comment by jaraco** [comment]
It's possible you could rewrite the docstrings... Perhaps in conf.py

**Comment by funkyfuture** [comment]
i amended changes as dicussed. i did a local preview this time.
i did some research, but found nothing to alter the documented method's signatures.

**Comment by funkyfuture** [comment]
the theme change was necessary to get the html built.

**Comment by funkyfuture** [comment]
leaving this note here, hope to come back at it some day.
there are actually hooks when sphinx generates a docstring: http://sphinx-doc.org/ext/autodoc.html#docstring-preprocessing

**Pull request merged**
