### PR TITLE
List perf

### PR DESCRIPTION
**Pull request by nmaier**
Initial implementation of the stuff I mentioned in #115

There is a slight possibility that this will break something, should somebody have defined a `_next_class` that somehow does not derive from `Path` and therefore lacks the new `_prepared_*` methods, but the chance of that is minute I think.

Still need to actually perf-test this, tho

### CODE REVIEW

**Comment by jaraco** [comment]
Thanks for putting this together, and sorry for not having reviewed it sooner. It's possible when I saw your last message, I decided to await your perf test results. Or I might have just missed it.

The first commit around `_always_unicode` looks sound. Thanks for committing that separately.

The remainder of this PR represents a pretty typical performance/simplicity tradeoff. While the performance improvements are fairly easily measurable, the effect on code complexity and cognitive burden by adding these changes is less easily measured, but my instinct is that the added complexity may not be worth the benefit (as for me, cognitive time is worth many orders of magnitude more than computing time).

You've done an excellent job factoring out much of the complexity into helper methods (e.g. _prepared_fnmatch), leaving little room for improvement.

My biggest concern is that the simple intent is wrapped up with the performance optimizations. I'm almost tempted to suggest instead creating a Path subclass with these optimizations. Maybe call it FastPath or PreparingPath or similar and have it (a) declare itself as an optimized version of the less-efficient Path, (b) supply the helper methods (_prepared*), and (c) override the necessary methods to invoke the optimizations.

Such an approach, while kinda messy in its own right, has the advantage of maintaining the existing simple implementation as the reference implementation, separating the optimization from the function, allowing a user to bypass the optimization if needed, but still exposing the optimization readily. We could even consider renaming Path to SimplePath and then exposing FastPath as Path, if we believe the optimized implementation should be the preferred one for most users.

The biggest downside I see to the approach I'm suggesting is that it does create a bit of redundancy and maintenance burden. Probably tests need to be run on both implementations.

Let me know what you think.

**Comment by jaraco** [comment]
I was going to go ahead and pull in the _always_unicode optimization. I had the code ready in master, but decided to run some tests.

I ran some performance tests on the _always_unicode optimization, and my results indicate the performance impact is negligible. I created a directory with 1000 files and then used the [timeit](https://docs.python.org/3.6/library/timeit.html) module to assess the performance. I start off with the optimized code in master, then switch to the last release (8.2.1), then switch back:

```
$ mkdir target
$ for i in {0001..1000}
for> do
for>   echo "some text" > "target/file_${i}.txt"
for> done
$ python -m timeit 'import path; path.Path(".").listdir("target")'
10000 loops, best of 3: 161 usec per loop
$ hg update 8.2.1
2 files updated, 0 files merged, 0 files removed, 0 files unresolved
(leaving bookmark master)
$ python -m timeit 'import path; path.Path(".").listdir("target")'
10 loops, best of 3: 162 usec per loop
$ python -m timeit 'import path; path.Path(".").listdir("target")'
10000 loops, best of 3: 165 usec per loop
$ hg update master
2 files updated, 0 files merged, 0 files removed, 0 files unresolved
(activating bookmark master)
$ python -m timeit 'import path; path.Path(".").listdir("target")'
10 loops, best of 3: 164 usec per loop
$ python -m timeit 'import path; path.Path(".").listdir("target")'
10000 loops, best of 3: 170 usec per loop
```

As you can see, I'm getting a low of 161µs and a high of 170µs, with the best time for the non-optimized time being comparable to the best for the optimized, and the worst for the optimized being worse than that for the non-optimized. Therefore, I don't think it's worth the change.

**Comment by jaraco** [comment]
Thinking that maybe the setup cost is overshadowing the impact, I re-ran the tests against master and 8.2.1 constructing the path in setup and only running the listdir in the test loop.

```
$ python -m timeit -s 'import path; p = path.Path(".")' 'p.listdir("target")'
10000 loops, best of 3: 161 usec per loop
$ hg update 8.2.1
2 files updated, 0 files merged, 0 files removed, 0 files unresolved
(leaving bookmark master)
$ python -m timeit -s 'import path; p = path.Path(".")' 'p.listdir("target")'
10000 loops, best of 3: 164 usec per loop
```

Still the results were comparable.

**Comment by nmaier** [comment]
>Thanks for putting this together, and sorry for not having reviewed it sooner. It's possible when I saw your last message, I decided to await your perf test results. Or I might have just missed it.

My reply is late too 😬 


Your beefy box and synthetic test directory (with reasonably short ascii-only file names) doing loops in usecs isn't really significant for what this is trying to achieve 😉 

Here are some real world results on a my real life Atom SoC I mentioned in #115 (my patches rebased on your master)

```txt
$ python3 --version
Python 3.6.0

$ python3 -c 'import path; p = path.Path("."); print(len(p.listdir()))'
2165

$ git checkout upstream/master
$ python3 -m timeit -s 'import path; p = path.Path(".")' 'p.listdir()'
10 loops, best of 3: 382 msec per loop

$ git checkout list-perf
$ python3 -m timeit -s 'import path; p = path.Path(".")' 'p.listdir()'
10 loops, best of 3: 164 msec per loop

$ git checkout upstream/master
$ python3 -m timeit -s 'import path; p = path.Path(".")' 'p.listdir()'
10 loops, best of 3: 390 msec per loop

$ git checkout list-perf
$ python3 -m timeit -s 'import path; p = path.Path(".")' 'p.listdir()'
10 loops, best of 3: 171 msec per loop
```

My patches on top of master will take only 40-50% of the time current master takes when calling `listdir()` without parameters, and that's a massive reduction in my book.
This minimark tested the non-pattern performance (which the 2nd commit improves).

So commit 1 and 2 are simple enough and do not really add much complexity, yet have massive improvements for the cases they were done for.

Now for some `walk`ing
```txt
$ python3 -c 'import path; p = path.Path("."); print(len(list(p.walk())))'
51821

$ git checkout upstream/master
$ python3 -m timeit -s 'import path; p = path.Path(".")' 'list(p.walk())'
10 loops, best of 3: 15.7 sec per loop

$ git checkout list-perf
$ python3 -m timeit -s 'import path; p = path.Path(".")' 'list(p.walk())'
10 loops, best of 3: 9.8 sec per loop
```

So about 60-66% when there is no pattern...

And finally, let's do something with a pattern to see commit number 3 in action.
```txt
$ python3 -c 'import path; p = path.Path("."); print(len(list(p.walkfiles("*.jpg"))))'
39554

$ git checkout upstream/master
$ python3 -m timeit -s 'import path; p = path.Path(".")' 'list(p.walkfiles("*.jpg"))'
10 loops, best of 3: 23.5 sec per loop

$ git checkout list-perf
$ python3 -m timeit -s 'import path; p = path.Path(".")' 'list(p.walkfiles("*.jpg"))'
10 loops, best of 3: 13.7 sec per loop
```
So again, in the 60% range due to commit number 3.

These improvements across the board make it OK to take the slight increase in complexity in my opinion.

As for suggestions to make a `FastPreparedPath` class, I don't really see the point and the changes are not really that grave or confusing at all.
And if anything, there should be a `SlowAndSimplePath` with the optimized version being the default.

**Comment by jaraco** [comment]
I'd like to proceed with #120 for now.

**Pull request closed without merging**
