### PR TITLE
Replace use of distutils with a bespoke implementation of merge_tree

### PR DESCRIPTION
**Pull request by jaraco**
As reported in #141, and following the [copytree example](https://docs.python.org/3/library/shutil.html#copytree-example), I've started work on this replacement implementation.

### CODE REVIEW

**Comment by jaraco** [comment]
@snarkboojum Would you be willing to review this change?

**Comment by SnarkBoojum** [comment]
If you have a patch against the current version, I can add the patch to my packaging and upload to the "experimental" debian distribution, where it will get compiled and the tests run on all architectures, see for example what it gives for [this other package of mine](https://buildd.debian.org/status/package.php?p=flint-arb&suite=experimental).

**Comment by jaraco** [comment]
```diff
diff --git a/path.py b/path.py
index cbdfee7..def8567 100644
--- a/path.py
+++ b/path.py
@@ -59,7 +59,6 @@ import operator
 import re
 import contextlib
 import io
-import distutils.dir_util
 import importlib
 import itertools
 
@@ -95,6 +94,7 @@ if PY2:
     getcwdu = os.getcwdu
     map = itertools.imap
     FileNotFoundError = OSError
+    itertools.filterfalse = itertools.ifilterfalse
 
 
 @contextlib.contextmanager
@@ -1417,34 +1417,55 @@ class Path(text_type):
 
     cd = chdir
 
-    def merge_tree(self, dst, symlinks=False, *args, **kwargs):
+    def merge_tree(
+            self, dst, symlinks=False,
+            # *
+            update=False,
+            copy_function=shutil.copy2,
+            ignore=lambda dir, contents: []):
         """
         Copy entire contents of self to dst, overwriting existing
         contents in dst with those in self.
 
-        If the additional keyword `update` is True, each
-        `src` will only be copied if `dst` does not exist,
-        or `src` is newer than `dst`.
-
-        Note that the technique employed stages the files in a temporary
-        directory first, so this function is not suitable for merging
-        trees with large files, especially if the temporary directory
-        is not capable of storing a copy of the entire source tree.
-        """
-        update = kwargs.pop('update', False)
-        with TempDir() as _temp_dir:
-            # first copy the tree to a stage directory to support
-            #  the parameters and behavior of copytree.
-            stage = _temp_dir / str(hash(self))
-            self.copytree(stage, symlinks, *args, **kwargs)
-            # now copy everything from the stage directory using
-            #  the semantics of dir_util.copy_tree
-            distutils.dir_util.copy_tree(
-                stage,
-                dst,
-                preserve_symlinks=symlinks,
-                update=update,
+        To avoid overwriting newer files, supply a copy function
+        wrapped in ``only_newer``. For example::
+
+            src.merge_tree(dst, copy_function=only_newer(shutil.copy2))
+        """
+        dst = self._next_class(dst)
+        dst.makedirs_p()
+
+        if update:
+            warnings.warn(
+                "Update is deprecated; "
+                "use copy_function=only_newer(shutil.copy2)",
+                DeprecationWarning,
             )
+            copy_function = only_newer(copy_function)
+
+        sources = self.listdir()
+        _ignored = ignore(self, [item.name for item in sources])
+
+        def ignored(item):
+            return item.name in _ignored
+
+        for source in itertools.filterfalse(ignored, sources):
+            dest = dst / source.name
+            if symlinks and source.islink():
+                target = source.readlink()
+                target.symlink(dest)
+            elif source.isdir():
+                source.mergetree(
+                    dest,
+                    symlinks=symlinks,
+                    update=update,
+                    copy_function=copy_function,
+                    ignore=ignore,
+                )
+            else:
+                copy_function(source, dest)
+
+        self.copystat(dst)
 
     #
     # --- Special stuff from os
@@ -1579,6 +1600,23 @@ class Path(text_type):
         return functools.partial(SpecialResolver, cls)
 
 
+def only_newer(copy_func):
+    """
+    Wrap a copy function (like shutil.copy2) to return
+    the dst if it's newer than the source.
+    """
+    @functools.wraps(copy_func)
+    def wrapper(src, dst, *args, **kwargs):
+        is_newer_dst = (
+            dst.exists()
+            and dst.getmtime() >= src.getmtime()
+        )
+        if is_newer_dst:
+            return dst
+        return copy_func(src, dst, *args, **kwargs)
+    return wrapper
+
+
 class SpecialResolver(object):
     class ResolverScope:
         def __init__(self, paths, scope):
diff --git a/test_path.py b/test_path.py
index eb10214..d149b08 100644
--- a/test_path.py
+++ b/test_path.py
@@ -855,6 +855,20 @@ class TestMergeTree:
         assert self.subdir_b.isdir()
         assert self.subdir_b.listdir() == [self.subdir_b / self.test_file.name]
 
+    def test_only_newer(self):
+        """
+        merge_tree should accept a copy_function in which only
+        newer files are copied and older files do not overwrite
+        newer copies in the dest.
+        """
+        target = self.subdir_b / 'testfile.txt'
+        target.write_text('this is newer')
+        self.subdir_a.merge_tree(
+            self.subdir_b,
+            copy_function=path.only_newer(shutil.copy2),
+        )
+        assert target.text() == 'this is newer'
+
 
 class TestChdir:
     def test_chdir_or_cd(self, tmpdir):
```

**Comment by SnarkBoojum** [comment]
Ok, it's uploaded, let's see how it fares ; the logs will be [here](https://buildd.debian.org/status/package.php?p=path.py&suite=experimental) (version 11.3.0-1)  when the package will get treated.

**Pull request merged**
